# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 90, 321, 451))
        self.listWidget.setObjectName("listWidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(360, 90, 411, 451))
        self.textBrowser.setObjectName("textBrowser")
        self.btnSendEmail = QtWidgets.QPushButton(self.centralwidget)
        self.btnSendEmail.setGeometry(QtCore.QRect(20, 10, 41, 41))
        self.btnSendEmail.setText("")
        self.btnSendEmail.setIconSize(QtCore.QSize(30, 30))
        self.btnSendEmail.setObjectName("btnSendEmail")
        self.btnRefresh = QtWidgets.QPushButton(self.centralwidget)
        self.btnRefresh.setGeometry(QtCore.QRect(110, 10, 41, 41))
        self.btnRefresh.setText("")
        self.btnRefresh.setIconSize(QtCore.QSize(30, 30))
        self.btnRefresh.setObjectName("btnRefresh")
        self.labelMainWin = QtWidgets.QLabel(self.centralwidget)
        self.labelMainWin.setGeometry(QtCore.QRect(20, 550, 401, 21))
        self.labelMainWin.setText("")
        self.labelMainWin.setObjectName("labelMainWin")
        self.btnUnseen = QtWidgets.QPushButton(self.centralwidget)
        self.btnUnseen.setGeometry(QtCore.QRect(160, 10, 41, 41))
        self.btnUnseen.setText("")
        self.btnUnseen.setIconSize(QtCore.QSize(30, 30))
        self.btnUnseen.setObjectName("btnUnseen")
        self.btnSendet = QtWidgets.QPushButton(self.centralwidget)
        self.btnSendet.setGeometry(QtCore.QRect(210, 10, 41, 41))
        self.btnSendet.setText("")
        self.btnSendet.setIconSize(QtCore.QSize(30, 30))
        self.btnSendet.setObjectName("btnSendet")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.btnDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(400, 10, 41, 41))
        self.btnDelete.setText("")
        self.btnDelete.setIconSize(QtCore.QSize(30, 30))
        self.btnDelete.setObjectName("btnDelete")
        self.btnReply = QtWidgets.QPushButton(self.centralwidget)
        self.btnReply.setGeometry(QtCore.QRect(300, 10, 41, 41))
        self.btnReply.setText("")
        self.btnReply.setIconSize(QtCore.QSize(30, 30))
        self.btnReply.setObjectName("btnReply")
        self.btnHandOff = QtWidgets.QPushButton(self.centralwidget)
        self.btnHandOff.setGeometry(QtCore.QRect(350, 10, 41, 41))
        self.btnHandOff.setText("")
        self.btnHandOff.setIconSize(QtCore.QSize(30, 30))
        self.btnHandOff.setObjectName("btnHandOff")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
